name: tag-demo
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify git commit sha to build image from'

  workflow_call:
    inputs:
      workflowsha:
        required: true
        type: string
      triggertype:
        required: true
        type: string
    secrets:
      ROLE_ID:
        required: true
      SECRET_ID:
        required: true
      GH_PAT:
        required: true

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: integration-deploy-${{ github.ref }}

  # On push to branch
  push:
    branches:
      - master

jobs:
  checkout_build_and_push_docker_image:
    runs-on: ubuntu-latest
    outputs:
      shortsha: ${{ steps.shortsha.outputs.shortsha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GH_PAT }}

      - name: Generate git sha(short)
        id: shortsha
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print git sha(short)
        run: echo "The git sha(short) is ${{ steps.shortsha.outputs.shortsha }}"

      - name: Run script file
        run: |
          chmod +x ./tag_generator.sh
          ./tag_generator.sh latest_int second_latest_int third_latest_int
        shell: bash

