name: tag-demo
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify git commit sha to build image from'
      deployto:
        type: choice
        description: 'Deploy the built image on environment.'
        options:
          - None
          - Integration
          - Integration and Qa

  # On push to branch
  push:
    branches:
      - master

jobs:
  checkout_build_and_push_docker_image:
    runs-on: ubuntu-latest
    outputs:
      shortsha: ${{ steps.shortsha.outputs.shortsha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
          token: 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

      - name: Generate git sha(short)
        id: shortsha
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print git sha(short)
        run: echo "The git sha(short) is ${{ steps.shortsha.outputs.shortsha }}"

      - name: Run script file
        run: |
            chmod +x ./.github/scripts/build.sh
            ./.github/scripts/build.sh
        shell: bash


